apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: menghi.uy
  namespace: external-dns
spec:
  endpoints:
    - dnsName: menghi.uy
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.1.221
    - dnsName: "*.menghi.uy"
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.1.221
