apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/dex
  prune: true
  dependsOn:
    - name: namespaces
    - name: external-secrets
    - name: external-secrets-config
  sourceRef:
    kind: GitRepository
    name: flux-system
