apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: dex
  chart:
    spec:
      chart: dex
      version: '0.24.0'
      sourceRef:
        kind: HelmRepository
        name: dex
      interval: 5m
  releaseName: dex
  values:
    envFrom:
      - secretRef:
          name: dex-github-connector
      - secretRef:
          name: dex-grafana-client
      - secretRef:
          name: dex-s3-proxy-client
      - secretRef:
          name: dex-envoy-client
    replicaCount: 2
    https:
      enabled: false
    ingress:
      enabled: false
    config:
      issuer: https://login.menghi.uy/dex/
      # The storage configuration determines where dex stores its state. Supported
      # options include SQL flavors and Kubernetes third party resources.
      #
      # See the documentation (https://dexidp.io/docs/storage/) for further information.
      storage:
        type: kubernetes
        config:
          inCluster: true

      # Configuration for the HTTP endpoints.
      web:
        http: 0.0.0.0:5556
      # Configuration for telemetry
      telemetry:
        http: 0.0.0.0:5558

      # Instead of reading from an external storage, use this list of clients.
      #
      # If this option isn't chosen clients may be added through the gRPC API.
      staticClients:
        - name: Envoy
          IDEnv: envoy_client_id
          secretEnv: envoy_client_secret
          redirectURIs:
            - https://storage.menghi.uy/oauth2/callback
            - https://prometheus.menghi.uy/oauth2/callback
        - name: S3Proxy
          IDEnv: s3proxy_client_id
          secretEnv: s3proxy_client_secret
          redirectURIs:
            - https://s3.menghi.uy/auth/dex/callback
        - name: Grafana
          IDEnv: grafana_client_id
          secretEnv: grafana_client_secret
          redirectURIs:
            - https://monitoring.menghi.uy/login/generic_oauth
      connectors:
        - type: github
          # Required field for connector id.
          id: github
          # Required field for connector name.
          name: GitHub
          config:
            # Credentials can be string literals or pulled from the environment.
            clientID: $GITHUB_CLIENT_ID
            clientSecret: $GITHUB_CLIENT_SECRET
            redirectURI: https://login.menghi.uy/dex/callback
            users:
              - cristianmenghi
            orgs:
              - name: cristianmenghi
                # A white list of teams. Only include group claims for these teams.
                teams:
                  - admin
            # Flag which indicates that all user groups and teams should be loaded.
            loadAllGroups: false

      # Let dex keep a list of passwords which can be used to login to dex.
      enablePasswordDB: false
