apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: teleport
  namespace: teleport
spec:
  interval: 5m
  url: https://charts.releases.teleport.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: teleport
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: teleport-cluster
      version: "18.6.0"
      sourceRef:
        kind: HelmRepository
        name: teleport
      interval: 5m
  releaseName: teleport-cluster
  values:
    chartMode: standalone
    clusterName: teleport.menghi.uy
    kubeClusterName: oci
    proxyListenerMode: multiplex
    auth:
      teleportConfig:
        auth_service:
          authentication:
            type: github
    authentication:
      type: github
      localAuth: true
      secondFactor: on
    highAvailability:
      replicaCount: 1
    operator:
      enabled: true
    ingress:
      enabled: false
    proxy:
      highAvailability:
        replicaCount: 1
      service:
        type: ClusterIP
