apiVersion: resources.teleport.dev/v2
kind: TeleportApp
metadata:
  name: kibana
  namespace: teleport
spec:
  app:
    name: kibana
    uri: "https://elastic-kb-http.elastic-system.svc.cluster.local:5601"
    insecure_skip_verify: true
    labels:
      env: "produccion"
      app: "kibana"
