apiVersion: resources.teleport.dev/v1
kind: TeleportAppV3
metadata:
  name: kibana
  namespace: teleport
  labels:
    env: "produccion"
    app: "kibana"
spec:
  uri: "https://elastic-kb-http.elastic-system.svc.cluster.local:5601"
  insecure_skip_verify: true
