apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/falco
  prune: true
  dependsOn:
    - name: namespaces
    - name: longhorn # Might need storage for rules if configured, but generally good to wait for base infra
  sourceRef:
    kind: GitRepository
    name: flux-system
