---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: flux-system
spec:
  interval: 1h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: security-system
spec:
  interval: 1h
  chart:
    spec:
      chart: falco
      version: "^4.22.0"  # Including Falco 0.42.0+ to definitely fix CRI panic
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    # Affinity para nodos ARM64
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64

    # Driver eBPF para ARM64 (NIVEL RAÍZ)
    driver:
      kind: modern_ebpf

    # Forzar imagen Falco 0.42.0 (bug fix)
    image:
      tag: 0.42.0

    # Deshabilitar Docker y Containerd (solo usar CRI-O)
    docker:
      enabled: false
    
    containerd:
      enabled: false

    # Configuración de Falco
    falco:
      # Métricas nativas de Prometheus
      metrics:
        enabled: true
        interval: 15s
      
      # Deshabilitar gRPC
      grpc:
        enabled: false
      
      grpc_output:
        enabled: false
      
      # Logs a stdout
      stdout_output:
        enabled: true
      
      # Enviar eventos a Falcosidekick vía HTTP
      http_output:
        enabled: true
        url: "http://falcosidekick.security-system.svc.cluster.local:2801"

    # ServiceMonitor para que Prometheus descubra las métricas
    serviceMonitor:
      enabled: true
