---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: flux-system
spec:
  interval: 1h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: security-system
spec:
  interval: 1h
  chart:
    spec:
      chart: falco
      version: "^4.0.0"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    falco:
      # Use eBPF driver for OCI ARM nodes
      driver:
        kind: ebpf
      
      # Configure CRI-O socket for Oracle Cloud (Default for OCI)
      # This helps avoid the panic in criEngine
      container_engines:
        cri:
          enabled: true
          sockets:
            - /run/crio/crio.sock
      
      # Enable gRPC for falco-exporter
      grpc:
        enabled: true
        bind_address: "0.0.0.0:5060"
      
      # Standard output to stdout
      stdout_output:
        enabled: true
      
      # Affinity for ARM64 (Oracle Cloud Free Tier)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64

      grpc_output:
        enabled: false
