---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: flux-system
spec:
  interval: 1h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: security-system
spec:
  interval: 1h
  chart:
    spec:
      chart: falco
      version: "^4.0.0"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    # 1. Affinity for the DaemonSet (TOP LEVEL)
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64

    falco:
      # 2. Main Falco Configuration
      driver:
        kind: ebpf
      
      # explicit CRI-O socket
      container_engines:
        docker:
          enabled: false
        cri:
          enabled: true
          sockets:
            - /run/crio/crio.sock
        containerd:
          enabled: false
      
      # 3. Enable Built-in Prometheus Metrics (Replaces falco-exporter)
      metrics:
        enabled: true
        interval: 15s
        output_format: prometheus
      
      # 4. Disable gRPC for now to avoid TLS errors/panic 
      # (Metrics don't need it)
      grpc:
        enabled: false
      
      grpc_output:
        enabled: false

      stdout_output:
        enabled: true

    # 5. ServiceMonitor for the built-in metrics
    serviceMonitor:
      enabled: true
