apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 5m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.10.1'
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 5m
  releaseName: longhorn
  values:
    image:
      longhorn:
        manager:
          repository: docker.io/longhornio/longhorn-manager
        engine:
          repository: docker.io/longhornio/longhorn-engine
        ui:
          repository: docker.io/longhornio/longhorn-ui
        instanceManager:
          repository: docker.io/longhornio/longhorn-instance-manager
        shareManager:
          repository: docker.io/longhornio/longhorn-share-manager
        backingImageManager:
          repository: docker.io/longhornio/backing-image-manager
    defaultSettings:
      storageMinimalAvailablePercentage: 10
    persistence:
      defaultClassReplicaCount: 2
    ingress:
      enabled: false
