apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oracle-vault
spec:
  provider:
    oracle:

      # REPLACE WITH YOUR VAULT OCID
      vault: "REPLACE_WITH_VAULT_OCID"
      # REPLACE WITH YOUR REGION (e.g., us-ashburn-1)
      region: "REPLACE_WITH_REGION"
      auth:
        # REPLACE WITH THE EXTERNAL SECRETS USER OCID
        user: "REPLACE_WITH_USER_OCID"
        # REPLACE WITH YOUR TENANCY OCID
        tenancy: "REPLACE_WITH_TENANCY_OCID"
        principalType: UserPrincipal
        secretRef:
          privatekey:
            name: oracle-vault
            key: privateKey
            namespace: external-secrets
          fingerprint:
            name: oracle-vault
            key: fingerprint
            namespace: external-secrets