---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: flux-system
spec:
  interval: 1h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falcosidekick
  namespace: security-system
spec:
  interval: 1h
  chart:
    spec:
      chart: falcosidekick
      version: "^0.9.0"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    # Configuración de Falcosidekick
    config:
      debug: true
    
    # Inyectar credenciales desde Secret para evitar texto plano en git
    extraEnv:
      - name: FALCOSIDEKICK_UI_USER
        valueFrom:
          secretKeyRef:
            name: falcosidekick-ui-secret
            key: auth
      
    # Habilitar WebUI
    webui:
      enabled: true
      # Configuración de la UI
      redis:
        storageEnabled: true
      
    # Affinity para ARM64
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    
    # Service para la UI
    service:
      type: ClusterIP
      port: 2801
