apiVersion: apps/v1
kind: Deployment
metadata:
  name: picoclaw
  namespace: picoclaw
  labels:
    app.kubernetes.io/name: picoclaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: picoclaw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: picoclaw
    spec:
      containers:
        - name: picoclaw
          image: docker.io/sipeed/picoclaw:launcher
          imagePullPolicy: IfNotPresent
          env:
            - name: PICOCLAW_GATEWAY_HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 18800
              name: launcher
            - containerPort: 18790
              name: gateway
          volumeMounts:
            - name: data
              mountPath: /root/.picoclaw
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: picoclaw-data
