apiVersion: v1
kind: Service
metadata:
  name: picoclaw
  namespace: picoclaw
  labels:
    app.kubernetes.io/name: picoclaw
spec:
  type: ClusterIP
  ports:
    - port: 18800
      targetPort: 18800
      protocol: TCP
      name: launcher
    - port: 18790
      targetPort: 18790
      protocol: TCP
      name: gateway
  selector:
    app.kubernetes.io/name: picoclaw
