apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-proxy-creds
  namespace: core
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: oracle-vault
    kind: ClusterSecretStore
  target:
    name: s3-proxy-creds
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: tourenbuch-s3-access-key
    - secretKey: AWS_SECRET_KEY_ID
      remoteRef:
        key: tourenbuch-s3-secret-key
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: tourenbuch-s3-endpoint
