apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowler
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/prowler
  prune: true
  dependsOn:
    - name: namespaces
    - name: external-dns
    - name: cert-manager

  sourceRef:
    kind: GitRepository
    name: flux-system
