apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1data
  namespace: f1replaytiming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1cache
  namespace: f1replaytiming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
