apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: oracle-lb
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "teleport.menghi.uy,login.menghi.uy,monitoring.menghi.uy,storage.menghi.uy,prometheus.menghi.uy"
          service.beta.kubernetes.io/oci-load-balancer-internal: "false"
          # Shape and NSG
          oci.oraclecloud.com/oci-network-security-groups: ${LB_NSG_ID}
          service.beta.kubernetes.io/oci-load-balancer-shape: flexible
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
