apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-es-http-tls
  namespace: elastic-system
spec:
  secretName: elastic-es-http-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "elk.menghi.uy"
    - "elastic-es-http.elastic-system.svc"
    - "elastic-es-http.elastic-system.svc.cluster.local"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-fleet-http-tls
  namespace: elastic-system
spec:
  secretName: elastic-fleet-http-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "elk.menghi.uy"
    - "elastic-agent-http.elastic-system.svc"
    - "elastic-agent-http.elastic-system.svc.cluster.local"
