apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-github-connector
  namespace: dex
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-github-connector
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: GITHUB_DEX_CLIENT_ID-v3
        version: CURRENT
        decodingStrategy: None
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: GITHUB_DEX_CLIENT_SECRET-v3
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-grafana-client
  namespace: dex
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-grafana-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        grafana_client_id: grafana
        grafana_client_secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-grafana-client-v3
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-s3-proxy-client
  namespace: dex
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-s3-proxy-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        s3proxy_client_id: s3-proxy
        s3proxy_client_secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-s3-proxy-client-secret-v3
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-envoy-client
  namespace: dex
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-envoy-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        envoy_client_id: envoy-gateway
        envoy_client_secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-envoy-client-secret-v3
        version: CURRENT
        decodingStrategy: None
