apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-api-keys
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: openclaw-api-keys
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: openclaw-api-keys-v3
        property: anthropic
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: openclaw-api-keys-v3
        property: openai
    - secretKey: DEEPSEEK_API_KEY
      remoteRef:
        key: openclaw-api-keys-v3
        property: deepseek
