apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-proxy-dex-client
  namespace: s3-proxy
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: s3-proxy-dex-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        client-id: s3-proxy
        S3_PROXY_DEX_CLIENT_SECRET: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-s3-proxy-client-secret-v3
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-proxy-creds
  namespace: s3-proxy
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: s3-proxy-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_KEY_ID: "{{ .AWS_SECRET_KEY_ID }}"
        S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: tourenbuch-s3-access-key
    - secretKey: AWS_SECRET_KEY_ID
      remoteRef:
        key: tourenbuch-s3-secret-key
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: tourenbuch-s3-endpoint
