apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oracle-vault
spec:
  provider:
    oracle:
      vault: "ocid1.vault.oc1.iad.ejuu5iv6aahkc.abuwcljrnjdggmki2w66lvb6kosi3vbolwvo3wvjahyzmmvhgjoe2ntckdpq"
      region: "us-ashburn-1"
      auth:
        user: "ocid1.user.oc1..aaaaaaaaj5t6euyjqxiavdf32ixjhfaj3ld3kp3naph6ilkiu34eyp3y7fqq"
        tenancy: "ocid1.tenancy.oc1..aaaaaaaa6wxacfrre6md5xe3w5sh3gcusdx5i7ok6frn656r7hhnoeawayga"
        principalType: UserPrincipal
        secretRef:
          privatekey:
            name: oracle-vault
            key: privateKey
            namespace: external-secrets
          fingerprint:
            name: oracle-vault
            key: fingerprint
            namespace: external-secrets
