apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-token
  namespace: flux-system
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: receiver-token
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: github-flux-webhook-token
        version: CURRENT
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluxcd-github-token
  namespace: flux-system
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: fluxcd-github-token
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: github-fluxcd-token
        version: CURRENT
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluxcd-slack-webhook
  namespace: flux-system
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: fluxcd-slack-webhook
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: slack-fluxcd-token
        version: CURRENT
