apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: falco-exporter
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/falco-exporter
  prune: true
  dependsOn:
    - name: namespaces
    - name: kube-prometheus-stack
    - name: falco
  sourceRef:
    kind: GitRepository
    name: flux-system
