---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: falco-exporter
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/falcosecurity/charts/falco-exporter
  ref:
    tag: 0.10.0 # Latest stable version at this time, or use semver if supported
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: security-system
spec:
  interval: 1h
  chart:
    spec:
      chart: falco-exporter
      sourceRef:
        kind: OCIRepository
        name: falco-exporter
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true # Just in case
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled
  maxHistory: 3
  values:
    # Connect to Falco service (standard name is falco)
    falco:
      grpc:
        address: falco.security-system.svc.cluster.local:5060
    
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: false
    prometheusRules:
      enabled: false